### ISSUE TITLE
OGC & REST services fail when starting the docker composition as described in the README

### ISSUE THREAD

**Issue by jahow** [geoserver/geoserver-cloud#106]
Hi,

I have followed the instructions [here](https://github.com/geoserver/geoserver-cloud#running) for starting a docker composition using the "official" docker images. This results in multiple errors in the docker-compose logs, and eventually a state where only the `gateway`, `discovery`, `config`, `postgres-jdbcconfig`, `rabbitmq`, `catalog` services are running.

I have noticed this kind of errors in the services that eventually fail:
```
rest_1       | java.lang.NullPointerException: null
rest_1       | 	at org.geoserver.security.GeoServerSecurityManager.migrateFrom21(GeoServerSecurityManager.java:2123) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
rest_1       | 	at org.geoserver.security.GeoServerSecurityManager.doReload(GeoServerSecurityManager.java:424) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
rest_1       | 	at org.geoserver.security.GeoServerSecurityManager.reload(GeoServerSecurityManager.java:378) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
rest_1       | 	at org.geoserver.security.GeoServerSecurityManager.onApplicationEvent(GeoServerSecurityManager.java:353) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
rest_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:842) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
rest_1       | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
rest_1       | 	at org.geoserver.cloud.restconfig.RestConfigApplication.main(RestConfigApplication.java:21) ~[classes/:na]
rest_1       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
rest_1       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
rest_1       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
rest_1       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
rest_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[bin/:na]
rest_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[bin/:na]
rest_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[bin/:na]
rest_1       | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[bin/:na]
```

Without any surprises, doing a `curl` on the services fail:
```
$ curl "http://localhost:9090/ows?request=getcapabilities&service={WMS,WFS,WCS}"

[1/3]: http://localhost:9090/ows?request=getcapabilities&service=WMS --> <stdout>
--_curl_--http://localhost:9090/ows?request=getcapabilities&service=WMS
{"timestamp":"2021-10-19T12:04:29.711+00:00","path":"/ows","status":503,"error":"Service Unavailable","requestId":"c1e27b03-8"}
[2/3]: http://localhost:9090/ows?request=getcapabilities&service=WFS --> <stdout>
--_curl_--http://localhost:9090/ows?request=getcapabilities&service=WFS
{"timestamp":"2021-10-19T12:04:29.899+00:00","path":"/ows","status":503,"error":"Service Unavailable","requestId":"c1e27b03-9"}
[3/3]: http://localhost:9090/ows?request=getcapabilities&service=WCS --> <stdout>
--_curl_--http://localhost:9090/ows?request=getcapabilities&service=WCS

```

Versions used (i.e. tag of the docker images):
* 1.0-SNAPSHOT ([this commit](https://github.com/geoserver/geoserver-cloud/commit/7c5f2904d87c8edf04d3ac3ea83adee555168ff9))
* 1-0-RC1
Results were identical with both.

Thanks a lot for this project, hope this helps!

**Comment by jahow** [comment]
It worked with the docker-compose provided above, with the following commands:
```bash
$ wget https://raw.githubusercontent.com/geoserver/geoserver-cloud/main/docs/deploy/docker-compose/stable/shared_datadir/docker-compose.yml
$ sed -i 's/-RC1/-SNAPSHOT/' docker-compose.yml
$ docker-compose -f docker-compose.yml --compatibility up -d
$ curl "http://localhost:9090/ows?request=getcapabilities&service={WMS,WFS,WCS}"
```

I guess this issue should stay opened since this is still an undocumented (and probably temporary) process.
