### ISSUE TITLE
Failed run services with local profile in Intellij IDEA

### ISSUE THREAD

**Issue by andermirik** [geoserver/geoserver-cloud#213]
I want to debug some logic inside microservices. For example `web-ui`. When i run it with profile `local` i have output like this:
I use OS Windows 10 21H2.

```
2022-03-22 00:34:31.677  INFO 292 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-03-22 00:34:32.286 DEBUG 292 --- [           main] o.s.retry.support.RetryTemplate          : Retry: count=0
2022-03-22 00:34:32.645  INFO 292 --- [           main] o.g.cloud.web.app.WebUIApplication       : The following profiles are active: webui_service
2022-03-22 00:34:34.475  WARN 292 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [jar:gs-authkey-.*!/applicationContext.xml]; nested exception is org.springframework.core.NestedIOException: Invalid URI [jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
2022-03-22 00:34:34.563 ERROR 292 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [jar:gs-authkey-.*!/applicationContext.xml]; nested exception is org.springframework.core.NestedIOException: Invalid URI [jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitionsApplyingFilters(FilteringXmlBeanDefinitionReader.java:155) ~[classes/:na]
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitions(FilteringXmlBeanDefinitionReader.java:94) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:203) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromImportedResources$0(ConfigurationClassBeanDefinitionReader.java:390) ~[spring-context-5.3.15.jar:5.3.15]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:354) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:156) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.geoserver.cloud.web.app.WebUIApplication.main(WebUIApplication.java:20) ~[classes/:na]
Caused by: org.springframework.core.NestedIOException: Invalid URI [jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:128) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.core.io.UrlResource.getURI(UrlResource.java:215) ~[spring-core-5.3.15.jar:5.3.15]
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitionsApplyingFilters(FilteringXmlBeanDefinitionReader.java:130) ~[classes/:na]
	... 20 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at java.base/java.net.URI$Parser.fail(URI.java:2974) ~[na:na]
	at java.base/java.net.URI$Parser.checkChars(URI.java:3145) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3181) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
	at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:381) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:370) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:125) ~[spring-core-5.3.15.jar:5.3.15]
	... 22 common frames omitted

org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [jar:gs-authkey-.*!/applicationContext.xml]; nested exception is org.springframework.core.NestedIOException: Invalid URI [jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitionsApplyingFilters(FilteringXmlBeanDefinitionReader.java:155)
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitions(FilteringXmlBeanDefinitionReader.java:94)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:203)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromImportedResources$0(ConfigurationClassBeanDefinitionReader.java:390)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:354)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:156)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.geoserver.cloud.web.app.WebUIApplication.main(WebUIApplication.java:20)
Caused by: org.springframework.core.NestedIOException: Invalid URI [jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:128)
	at org.springframework.core.io.UrlResource.getURI(UrlResource.java:215)
	at org.geoserver.cloud.config.factory.FilteringXmlBeanDefinitionReader.loadBeanDefinitionsApplyingFilters(FilteringXmlBeanDefinitionReader.java:130)
	... 20 more
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\andermirik\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar!/
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
	at java.base/java.net.URI$Parser.parse(URI.java:3181)
	at java.base/java.net.URI.<init>(URI.java:623)
	at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:381)
	at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:370)
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:125)
	... 22 more

Process finished with exit code -1

```

**Comment by andermirik** [comment]
It would be nice if you showed how you run for debugging

**Comment by groldan** [comment]
something like:

```bash
alias dcj='docker-compose -f docker-compose.yml -f docker-compose-jdbcconfig.yml --compatibility'
dcj up -d
```

And then run from the IDE using **both** the `local` and `jdbcconfig` profiles. 
![image](https://user-images.githubusercontent.com/207423/164074732-07fa4600-76c3-4cc5-a2f6-ba29f71bd913.png)

If testing with the `datadir` profile, then
```bash
alias dcd='docker-compose -f docker-compose.yml -f docker-compose-shared_datadir.yml --compatibility'
dcd up -d
```
and run from IDE with profiles `local` and `datadir` instead.

**Comment by groldan** [comment]
Closing due to inactivity. Feel free to re-open if you need more info.
