### ISSUE TITLE
Failed to copy Geoserver data directory to Geoserver Cloud

### ISSUE THREAD

**Issue by giancastro** [geoserver/geoserver-cloud#252]
I already copied the data directory between Geoserver to Geoserver, but to Geoserver Cloud it doesn't work and the Kubernetes pod gets CrashLoopBackOff.

Does this data copy process need to be done in a different way?

The file `/opt/app/data_directory/filelocks/resourcestore.locks` exists, but I can't remove or create again.

LOG:
```

2022-06-23 18:31:50.293  WARN 1 --- [           main] org.geoserver                            : Failed to load data store 'postgis'

com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : org.springframework.beans.factory.BeanCreationException
cause-message       : Error creating bean with name 'authenticationManager' defined in class path resource [org/geoserver/cloud/config/security/GeoServerSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.cloud.security.CloudGeoServerSecurityManager]: Factory method 'cloudAuthenticationManager' threw exception; nested exception is java.lang.IllegalStateException: Locks file does not exist: /opt/app/data_directory/filelocks/resourcestore.locks
class               : org.geoserver.catalog.impl.DataStoreInfoImpl
required-type       : org.geoserver.catalog.impl.DataStoreInfoImpl
converter-type      : org.geoserver.config.util.XStreamPersister$StoreInfoConverter
line number         : 42
version             : 2.21.0-CLOUD
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81) ~[xstream-1.4.19.jar:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[xstream-1.4.19.jar:1.4.19]
....
....
....
Caused by: java.io.FileNotFoundException: /opt/app/data_directory/filelocks/resourcestore.locks (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method) ~[na:na]
	at java.base/java.io.RandomAccessFile.open(Unknown Source) ~[na:na]
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source) ~[na:na]
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source) ~[na:na]
	at org.geoserver.platform.resource.NioFileLockProvider.openChannel(NioFileLockProvider.java:154) ~[gs-platform-2.21.0-CLOUD.jar:2.21.0-CLOUD]
	... 206 common frames omitted

```

**Comment by groldan** [comment]
May it be a file permissions problem?
If you're using the docker-compose version not it'll run the containers with UID and GID == `1000`: https://github.com/geoserver/geoserver-cloud/blob/main/docs/deploy/docker-compose/stable/shared_datadir/docker-compose.yml#L124

**Comment by giancastro** [comment]
I'm using Kubernetes. I added the `securityContext`, but the issue was related to the datastorage. I had to recreate the datastore to get it working.
