### ISSUE TITLE
Unable to create layers from Generalizing DataStore

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#302]
Context:
- GS Cloud with JDBC config and JDBC resource store
- Data are stored in a Postgis Database

Reproduced with:
- GS Cloud RC1.28 on Kubernetes deployed with Helm charts
- GS Cloud RC1.28 on Docker deployed with docker compose
- GS Cloud RC1.29 On Docker deployed with docker compose
- GS Cloud master code from GitHub deployed with docker compose

In all cases, when I try to create a layer from a generalizing DataStore from admin UI, I always have the following message:
`Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "f" is null
	at org.geoserver.data.gen.DSFinderRepository.getURLForLocation(DSFinderRepository.java:46)
	at org.geotools.data.gen.DSFinderRepository.getMapFromPropetryLocation(DSFinderRepository.java:81)
	at org.geotools.data.gen.DSFinderRepository.dataStore(DSFinderRepository.java:114)
	at org.geoserver.data.gen.DSFinderRepository.dataStore(DSFinderRepository.java:69)
	at org.geotools.data.gen.PreGeneralizedFeatureSource.getBaseFeatureSource(PreGeneralizedFeatureSource.java:113)
	at org.geotools.data.gen.PreGeneralizedFeatureSource.getSchema(PreGeneralizedFeatureSource.java:357)
	at org.geotools.data.gen.PreGeneralizedFeatureSource.getSchema(PreGeneralizedFeatureSource.java:67)
	at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:342)
	at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:325)
	at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:421)
	... 119 more`

**Comment by AlexGacon** [comment]
A more complete analysis shows that the problem is located in the GeoServer code base. An issue has been opened on JIRA (https://osgeo-org.atlassian.net/browse/GEOS-10952).
