### ISSUE TITLE
Enabling the geoserver configuration file in the pom file, unable to start

### ISSUE THREAD

**Issue by xgblack** [geoserver/geoserver-cloud#354]
Hello, after I activate the configuration of geoserver in the pom file, the module does not start properly, 'wms' that could not be found. when I de-configure it and use the jar built in the local repository it starts properly! 
May I ask what is the reason for this, can geoserver_submodule be used only after the build?  thanks!
```2023-08-31 23:03:37.931  WARN 41139 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getMapKvpReader' defined in class path resource [org/geoserver/cloud/gwc/config/core/WebMapServiceMinimalConfiguration.class]: 'getMapKvpReader' depends on missing bean 'wms'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'wms' available
2023-08-31 23:03:37.987 ERROR 41139 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'wms' that could not be found.


Action:

Consider defining a bean named 'wms' in your configuration.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getMapKvpReader' defined in class path resource [org/geoserver/cloud/gwc/config/core/WebMapServiceMinimalConfiguration.class]: 'getMapKvpReader' depends on missing bean 'wms'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'wms' available
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.geoserver.cloud.wms.app.WmsApplication.main(WmsApplication.java:17)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'wms' available`

**Comment by groldan** [comment]
Hi, I take you're trying to run a service from an IDE?

Yes, the geoserver_submodule is supposed to be built once and then just depend on it.
So just run `make deps` and forget about it, import only the geoserver-cloud projects to the IDE.
I've actually just removed geoserver_submodule from the root pom in this PR #355

**Comment by groldan** [comment]
closing as stale
