### ISSUE TITLE
Fix geoserver jdbcconfig's concurrency problem

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#64]
Happens when querying all layers concurrently for example.

```
catalog_1    | java.util.ConcurrentModificationException: null
catalog_1    | 	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[na:na]
catalog_1    | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
catalog_1    | Error has been observed at the following site(s):
catalog_1    | 	|_ checkpoint ⇢ Handler org.geoserver.cloud.catalog.api.v1.ReactiveCatalogController#findAll(String, ClassMappings) [DispatcherHandler]
catalog_1    | 	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
catalog_1    | 	|_ checkpoint ⇢ HTTP GET "/api/v1/catalog/layers/" [ExceptionHandlingWebHandler]
catalog_1    | Stack trace:
catalog_1    | 		at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[na:na]
catalog_1    | 		at java.base/java.util.HashMap$KeyIterator.next(Unknown Source) ~[na:na]
catalog_1    | 		at org.geoserver.jdbcconfig.internal.ConfigDatabase$CatalogReferenceUpdater.visit(ConfigDatabase.java:1795) ~[gs-jdbcconfig-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at org.geoserver.catalog.impl.LayerInfoImpl.accept(LayerInfoImpl.java:272) ~[gs-main-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at org.geoserver.jdbcconfig.internal.ConfigDatabase.resolveCatalog(ConfigDatabase.java:1175) ~[gs-jdbcconfig-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at org.geoserver.jdbcconfig.internal.ConfigDatabase.getById(ConfigDatabase.java:1083) ~[gs-jdbcconfig-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at org.geoserver.jdbcconfig.internal.ConfigDatabase$2.apply(ConfigDatabase.java:395) ~[gs-jdbcconfig-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at org.geoserver.jdbcconfig.internal.ConfigDatabase$2.apply(ConfigDatabase.java:391) ~[gs-jdbcconfig-2.18-SNAPSHOT.jar!/:2.18-SNAPSHOT]
catalog_1    | 		at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612) ~[guava-29.0-jre.jar!/:na]
catalog_1    | 		at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[guava-29.0-jre.jar!/:na]
catalog_1    | 		at com.google.common.collect.Iterators$5.computeNext(Iterators.java:636) ~[guava-29.0-jre.jar!/:na]
catalog_1    | 		at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141) ~[guava-29.0-jre.jar
```

**Comment by groldan** [comment]
Fixed upstream, closing.
