### ISSUE TITLE
Build error: org.geotools.jackson.databind.filter.dto.FilterSerializationTest fails

### ISSUE THREAD

**Issue by bartzwemmer** [geoserver/geoserver-cloud#88]
When building on:
* Windows 10 21H1
* Maven 3.8.1
* Java JDK 15.0.2 OpenJDK

The build tests fail for gt-jackson-bindings.

Log error:

`-------------------------------------------------------------------------------
Test set: org.geotools.jackson.databind.filter.dto.FilterSerializationTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.169 sec <<< FAILURE!
binaryTemporalOperators(org.geotools.jackson.databind.filter.dto.FilterSerializationTest)  Time elapsed: 0.015 sec  <<< FAILURE!
java.lang.AssertionError: expected: org.geotools.jackson.databind.filter.dto.Filter$BinaryTemporalOperator$AnyInteracts<Filter.BinaryTemporalOperator.AnyInteracts()> but was: org.geotools.jackson.databind.filter.dto.Filter$BinaryTemporalOperator$AnyInteracts<Filter.BinaryTemporalOperator.AnyInteracts()>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.geotools.jackson.databind.filter.dto.FilterSerializationTest.roundtripTest(FilterSerializationTest.java:29)
	at org.geotools.jackson.databind.filter.FilterRoundtripTest.testBinaryTemporalOperator(FilterRoundtripTest.java:244)
	at org.geotools.jackson.databind.filter.FilterRoundtripTest.binaryTemporalOperators(FilterRoundtripTest.java:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

`

**Comment by groldan** [comment]
Hey @bartzwemmer thanks for trying this out.
I haven't had a chance to look into it, but I'm betting it's due to Java 15 not being supported/tested yet.
Can you try with Java 11?

**Comment by securedimensions** [comment]
Building fails on 
* Ubuntu 20
* Maven 3.6.3
* OpenJDK 11

[org.geotools.jackson.databind.filter.dto.FilterSerializationTest.txt](https://github.com/geoserver/geoserver-cloud/files/6771396/org.geotools.jackson.databind.filter.dto.FilterSerializationTest.txt)

**Comment by bartzwemmer** [comment]
I just tried OpenJDK 11.0.2 and I still get the same error.

**Comment by groldan** [comment]
hey, hmmm.. I'll take a look asap

**Comment by groldan** [comment]
Should be fixed, I can't build on Windows though, but it doesn't look like it'd be a Windows-specific issue
